### ISSUE TITLE
Повторяющиеся элементы в RecyclerView

### ISSUE THREAD

**Issue by kalyashov** [matzuk/AutoLoadingRecyclerViewSample#1]
Здравствуйте! Реализовал все по вашему 2-му туториалу + смотрел на исходники с гитхаба. Все работает, посты подгружаются с сервера, но почему-то отображаются только первые 3 поста, при чем они чередуются, к примеру, если с сервера пришло 9 постов, то в ленте будет первые 3 поста по 3 раза. В чём может быть проблема?

**Comment by matzuk** [comment]
Добрый день!
Честно говоря, интересный кейс. Первое, что приходит в голову, а на сервер отдаются корректные offset и вообще он точно корректно работает?
Чтобы исключить, что виноват PaginationTool, можно вместо сервера подставить эмулятор, типа как в примере моем - EmulateResponseManager, и посмотреть на результат.
Либо, если Вы не против, могу глянуть Ваши исходники.

**Comment by kalyashov** [comment]
Да, сначала тоже подумал, что проблема в offset. Попробовал с эмулятором, как в примере, но ничего не изменилось. Сюда залил необходимый код -  [pagination](https://github.com/kalyashov/pagination)

**Comment by matzuk** [comment]
Сегодня посмотрю)

**Comment by matzuk** [comment]
А можете залить рабочий вариант? А то тут не хватает классов Post, PostType.

**Comment by kalyashov** [comment]
Могу, просто тут еще много другого кода, здесь Post, PostType - https://github.com/nemodevelopers/ProjectX_androidApp/tree/master/app/src/main/java/com/nemodevelopers/Models/Post

**Comment by matzuk** [comment]
Я продебажил ваше приложение. PaginationTool все время верно выдает offset, плюс в адаптере List<Post> listPosts тоже верно формируется. Проблема с отображением на RecyclerView. Где-то не верно у вас кэшируется.

**Comment by kalyashov** [comment]
Спасибо! Проверю это)
