### ISSUE TITLE
Feature request: Create a library

### ISSUE THREAD

**Issue by glureau** [matzuk/AutoLoadingRecyclerViewSample#7]
Hi there,
Your code looks promising, but I didn't find a library giving this ability. 
Would you create and maintain such a library?

**Comment by motornyimaksym** [comment]
@matzuk Maybe if you provide specifications for such kind of library I could try to implement it.

**Comment by matzuk** [comment]
Uf, @Yazon2006, do you have ideas for specification?

**Comment by motornyimaksym** [comment]
It depends on what users of this library expect to get from it) I'll think about variety of questions and possible use cases. @glureau It would be great if you have any detailed suggestions.

**Comment by glureau** [comment]
Hey! Sorry for the big delay, I was closing old issues and found this one. Originally I was suggesting to push the library on maven-central to be easy to use, but I may have missed the "Sample". Anyway, I don't think this issue is relevant anymore. Have a good day!
